/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jcbart12595' at '7/18/16 12:29 AM' with Gradle 2.12
 *
 * @author jcbart12595, @date 7/18/16 12:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
